In [1]:
import numpy as np
import torch

In [3]:
torch.randn(3)

tensor([-0.1406, -0.8039, -1.1212])

In [2]:
a = [[1,2,3],[2,3,3],[2,2,3,2,2]]

In [4]:
lena =[len(i) for i in a]

In [5]:
np.array(lena).max()

5

In [6]:
from typing import List, Tuple, Dict, Set, Union


In [7]:
List[float]

typing.List[float]

In [8]:
from torch.nn.utils.rnn import pack_padded_sequence, pad_packed_sequence

In [9]:
a = torch.tensor([[1,2,3],[6,0,0],[4,5,0]])
lengths = torch.tensor([3,1,2])
a_lengths, idx = lengths.sort(0, descending=True)
a_lengths, idx

(tensor([3, 2, 1]), tensor([0, 2, 1]))

In [10]:
_, un_idx = torch.sort(idx, dim=0)

In [11]:
a = a[idx]

In [12]:
a

tensor([[1, 2, 3],
        [4, 5, 0],
        [6, 0, 0]])

In [13]:
emb = torch.nn.Embedding(20,2,padding_idx=0)
lstm = torch.nn.LSTM(input_size=2, hidden_size=4, batch_first=True)
a_input = emb(a)
a_input 

tensor([[[ 0.0321, -0.3637],
         [ 1.9273, -0.2071],
         [-0.3575, -0.4427]],

        [[-0.8007,  0.1199],
         [ 0.3622, -0.9028],
         [ 0.0000,  0.0000]],

        [[-0.4836,  0.1002],
         [ 0.0000,  0.0000],
         [ 0.0000,  0.0000]]], grad_fn=<EmbeddingBackward>)

In [14]:
a_input.size()

torch.Size([3, 3, 2])

In [15]:
a_packed_input = torch.nn.utils.rnn.pack_padded_sequence(input=a_input, lengths=a_lengths, batch_first=True)
a_packed_input

PackedSequence(data=tensor([[ 0.0321, -0.3637],
        [-0.8007,  0.1199],
        [-0.4836,  0.1002],
        [ 1.9273, -0.2071],
        [ 0.3622, -0.9028],
        [-0.3575, -0.4427]], grad_fn=<PackPaddedSequenceBackward>), batch_sizes=tensor([3, 2, 1]), sorted_indices=None, unsorted_indices=None)

In [16]:
packed_out, _ = lstm(a_packed_input)

In [17]:
packed_out

PackedSequence(data=tensor([[ 0.0828,  0.0029,  0.1247, -0.0333],
        [ 0.0005,  0.0009,  0.0831, -0.1806],
        [ 0.0218,  0.0035,  0.0886, -0.1388],
        [ 0.1618,  0.0265,  0.1620,  0.0429],
        [ 0.1161,  0.0014,  0.2299, -0.0211],
        [ 0.1485,  0.0137,  0.2002, -0.0415]], grad_fn=<CatBackward>), batch_sizes=tensor([3, 2, 1]), sorted_indices=None, unsorted_indices=None)

In [18]:
out, _ = pad_packed_sequence(packed_out)
out

tensor([[[ 0.0828,  0.0029,  0.1247, -0.0333],
         [ 0.0005,  0.0009,  0.0831, -0.1806],
         [ 0.0218,  0.0035,  0.0886, -0.1388]],

        [[ 0.1618,  0.0265,  0.1620,  0.0429],
         [ 0.1161,  0.0014,  0.2299, -0.0211],
         [ 0.0000,  0.0000,  0.0000,  0.0000]],

        [[ 0.1485,  0.0137,  0.2002, -0.0415],
         [ 0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000]]], grad_fn=<CopySlices>)

In [19]:
out = torch.index_select(out, 0, un_idx)

In [20]:
out

tensor([[[ 0.0828,  0.0029,  0.1247, -0.0333],
         [ 0.0005,  0.0009,  0.0831, -0.1806],
         [ 0.0218,  0.0035,  0.0886, -0.1388]],

        [[ 0.1485,  0.0137,  0.2002, -0.0415],
         [ 0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000]],

        [[ 0.1618,  0.0265,  0.1620,  0.0429],
         [ 0.1161,  0.0014,  0.2299, -0.0211],
         [ 0.0000,  0.0000,  0.0000,  0.0000]]], grad_fn=<IndexSelectBackward>)

In [21]:
# torch.split
torch.split(torch.tensor([1,3,4,5,6,7]),2,0)

(tensor([1, 3]), tensor([4, 5]), tensor([6, 7]))

In [22]:
a = torch.tensor([
    [[1],[1]],
    [[2],[2]]
])
a.shape

torch.Size([2, 2, 1])

In [23]:
b = a.squeeze()

In [24]:
b.size()

torch.Size([2, 2])

In [25]:
torch.stack([b]*3, dim=0).size()

torch.Size([3, 2, 2])

In [26]:
b = 3
h = 2
dec_hidden =torch.randn((b,h))
src_len = 10
enc_hiddens_proj = torch.randn((b, src_len, h))

In [27]:
enc_hiddens_proj.shape, dec_hidden.shape

(torch.Size([3, 10, 2]), torch.Size([3, 2]))

In [28]:
b, src_len

(3, 10)

In [29]:
e_t = torch.bmm(dec_hidden.unsqueeze(dim=1), enc_hiddens_proj.view((b,h,src_len))).squeeze(dim=1)
e_t.size()

torch.Size([3, 10])

In [30]:
e_t = torch.bmm(enc_hiddens_proj, torch.unsqueeze(dec_hidden, dim=2)).squeeze(dim=2)

In [31]:
import torch.nn as nn

In [32]:
e_t

tensor([[ 6.2804,  1.4334,  0.6463, -8.6435, -3.2104, -3.1381,  2.3730,  1.4660,
          2.7911, -0.9780],
        [-0.7725,  1.7268,  1.5670,  0.5945, -0.6253, -2.1163,  1.4096,  1.6465,
          2.9342, -0.5334],
        [-1.5720, -2.5578,  2.6107,  0.7483,  0.0825, -0.9389, -0.9421, -1.1035,
          1.9941, -0.0621]])

In [33]:
m = nn.Softmax(dim =1)
m(e_t)

tensor([[9.3370e-01, 7.3310e-03, 3.3368e-03, 3.0819e-07, 7.0535e-05, 7.5825e-05,
         1.8760e-02, 7.5743e-03, 2.8498e-02, 6.5750e-04],
        [1.0991e-02, 1.3380e-01, 1.1405e-01, 4.3127e-02, 1.2734e-02, 2.8671e-03,
         9.7441e-02, 1.2348e-01, 4.4754e-01, 1.3961e-02],
        [7.8373e-03, 2.9246e-03, 5.1371e-01, 7.9778e-02, 4.0995e-02, 1.4761e-02,
         1.4715e-02, 1.2521e-02, 2.7728e-01, 3.5474e-02]])

In [34]:
nn.Softmax(dim =1)(e_t)

tensor([[9.3370e-01, 7.3310e-03, 3.3368e-03, 3.0819e-07, 7.0535e-05, 7.5825e-05,
         1.8760e-02, 7.5743e-03, 2.8498e-02, 6.5750e-04],
        [1.0991e-02, 1.3380e-01, 1.1405e-01, 4.3127e-02, 1.2734e-02, 2.8671e-03,
         9.7441e-02, 1.2348e-01, 4.4754e-01, 1.3961e-02],
        [7.8373e-03, 2.9246e-03, 5.1371e-01, 7.9778e-02, 4.0995e-02, 1.4761e-02,
         1.4715e-02, 1.2521e-02, 2.7728e-01, 3.5474e-02]])

In [35]:
alpha_t = nn.Softmax(dim=1)(e_t)

In [36]:
enc_hiddens = torch.randn((b, src_len, 2*h))

In [37]:
b, src_len

(3, 10)

In [38]:
alpha_t.shape, enc_hiddens.shape
# b, src_len; b, src_len, 2*h

(torch.Size([3, 10]), torch.Size([3, 10, 4]))

In [39]:
torch.squeeze(torch.bmm(torch.unsqueeze(alpha_t, 1), enc_hiddens),1)

tensor([[ 1.3908, -0.4664, -0.5403, -0.9161],
        [-0.1374,  0.6849, -0.5844, -0.0409],
        [ 0.3221,  0.1419,  0.4798, -0.0855]])