In [1]:
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

In [2]:
from util import torch_from_json

In [3]:
char_vectors = torch_from_json('./data/char_emb.json')

In [4]:
char_vectors.size()

torch.Size([1376, 64])

In [5]:
word_vectors = torch_from_json('./data/word_emb.json')

In [6]:
word_vectors.size()

torch.Size([88714, 300])

In [7]:
import json

with open('./data/char2idx.json', 'r') as fh:
    dict = json.load(fh)

In [10]:
len(dict.keys())

1376

In [11]:
char_vectors.size()

torch.Size([1376, 64])

In [6]:
bs, seq_len, word_len, char_dim = 5, 10, 16, 3

In [7]:
char_emb = torch.randn(bs, seq_len, word_len, char_dim)

In [8]:
char_emb[0, 0, :]

tensor([[-2.0958,  1.2418,  0.5318],
        [ 0.5192, -1.2130,  0.8903],
        [ 0.8926, -0.6093,  1.2144],
        [-0.9555, -0.3949,  1.0606],
        [-0.9214, -0.1123, -0.0781],
        [ 0.6793,  0.5488, -0.2245],
        [ 1.3626, -2.7125,  0.2707],
        [ 0.1926,  0.2943,  0.1235],
        [ 0.3701, -0.3281, -0.2328],
        [-2.3782,  0.5049, -1.2122],
        [-1.6244,  1.0623,  0.5459],
        [-0.6253,  0.5185,  0.2691],
        [ 1.0157, -1.0533, -0.6291],
        [ 1.5716, -0.6221,  0.6294],
        [ 0.4461, -1.0636, -0.7831],
        [ 1.7358,  0.9022, -1.2010]])

In [17]:
torch.max(char_emb, dim=2, keepdim=True)[0].squeeze(dim=2).size()

torch.Size([5, 10, 3])

In [23]:
char_vocab_size=1376
char_dim=200
bs, seq_len = 3, 10
word_len = 15

char_emb = nn.Embedding(char_vocab_size, char_dim, padding_idx=0)

nn.init.uniform_(char_emb.weight, 0, 1)

Parameter containing:
tensor([[0.3350, 0.0903, 0.2734,  ..., 0.5252, 0.4639, 0.0393],
        [0.0020, 0.8844, 0.4640,  ..., 0.8336, 0.9199, 0.2973],
        [0.1658, 0.2714, 0.9328,  ..., 0.8583, 0.3221, 0.7077],
        ...,
        [0.1121, 0.9791, 0.3217,  ..., 0.7889, 0.8806, 0.1389],
        [0.8267, 0.0046, 0.8031,  ..., 0.6728, 0.1201, 0.6872],
        [0.5187, 0.0235, 0.9183,  ..., 0.7303, 0.3601, 0.9505]],
       requires_grad=True)

In [16]:
char_idxs = torch.randint(1, 10, (bs, seq_len, word_len))

In [24]:
char_emb(char_idxs)

tensor([[[[0.0020, 0.8844, 0.4640,  ..., 0.8336, 0.9199, 0.2973],
          [0.0020, 0.8844, 0.4640,  ..., 0.8336, 0.9199, 0.2973],
          [0.8953, 0.5199, 0.2255,  ..., 0.4920, 0.0276, 0.2343],
          ...,
          [0.8658, 0.3679, 0.6383,  ..., 0.1796, 0.4250, 0.2373],
          [0.4639, 0.1899, 0.3157,  ..., 0.4475, 0.4756, 0.3617],
          [0.3134, 0.5052, 0.3596,  ..., 0.9910, 0.6245, 0.1356]],

         [[0.2502, 0.0579, 0.7748,  ..., 0.8201, 0.5729, 0.7141],
          [0.2502, 0.0579, 0.7748,  ..., 0.8201, 0.5729, 0.7141],
          [0.8658, 0.3679, 0.6383,  ..., 0.1796, 0.4250, 0.2373],
          ...,
          [0.2502, 0.0579, 0.7748,  ..., 0.8201, 0.5729, 0.7141],
          [0.4665, 0.4744, 0.7437,  ..., 0.1050, 0.2136, 0.3064],
          [0.8953, 0.5199, 0.2255,  ..., 0.4920, 0.0276, 0.2343]],

         [[0.8658, 0.3679, 0.6383,  ..., 0.1796, 0.4250, 0.2373],
          [0.6473, 0.8861, 0.2745,  ..., 0.2982, 0.5508, 0.2903],
          [0.2502, 0.0579, 0.7748,  ..., 0